services:
  backend:
    container_name: totlaunloc-backend
    build: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:backend
    environment:
      - SUPERUSER_EMAIL=
      - SUPERUSER_PASS=
      - ALLOWED_ORIGINS=https://totlaunloc.top,http://localhost:5573
    networks:
      - proxy
    restart: unless-stopped

  pocketbase:
    container_name: totlaunloc-db
    build: 
      context: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:database
      args:
        - SUPERUSER_EMAIL=mimiionescu07@gmail.com
        - SUPERUSER_PASS=12345678
    volumes:
      - /srv/totlaunloc/db:/pb/pb_data
    networks:
      - proxy
    restart: unless-stopped

  frontend:
    container_name: totlaunloc-frontend
    build: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:frontend
    environment:
      - PORT=5573
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true