services:
  backend:
    container_name: totlaunloc-backend
    build: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:backend
    environment:
      - SUPERUSER_EMAIL= #add superuser email set, after changing it in the pocketbase db
      - SUPERUSER_PASS=  #do the same for the password
      - ALLOWED_ORIGINS=https://totlaunloc.top,http://localhost:5573
    networks:
      - proxy
    restart: unless-stopped

  pocketbase:
    container_name: totlaunloc-db
    build: 
      context: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:database
      args:
        - SUPERUSER_EMAIL=api@api.com
        - SUPERUSER_PASS=changeme
    volumes:
      - /srv/totlaunloc/db:/pb/pb_data
    networks:
      - proxy
    restart: unless-stopped

  frontend:
    container_name: totlaunloc-frontend
    build: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:frontend
    environment:
      - PORT=5573
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true