services:
  totlaunloc-panel-backend:
    container_name: totlaunloc-backend
    build: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:backend
    volumes:
      - /srv/totlaunloc/backend/db.sqlite:/app/db.sqlite
    networks:
      - proxy
    restart: unless-stopped

  totlaunloc-panel-frontend:
    container_name: totlaunloc-frontend
    build: https://github.com/DrgDodge/TotLaUnLoc-panel.git#main:frontend
    environment:
      - PORT=5573
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true